//documented structs in the api:
#include <assert.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h> //need uintptr_t
#include <stdarg.h>
#include <stdio.h>
//there is another include for "hasht.h"

struct kastr_str {
    int ktype;
    char *str; //null terminated
    int len;
    int cap; //negative values mean memory is not owned by us (const char * passed to us)
};

struct kastr_list {
    int ktype;
    struct kastr_str *items;
    int len;
    int cap;
};

struct kastr_obj {
    union kastr_obj_u {
        int ktype;
        struct kastr_list list;
        struct kastr_str str;
    } u;
};
enum KASTR_RV {
    KASTR_OK = 0,
    KASTR_NOMEM,
    KASTR_SYNTAX_ERR,
    KASTR_RUNTIME_ERR,
    KASTR_NOT_FOUND_ERR,
};
enum KASTR_TYPE {
    KASTR_NULL = 0xd6,
    KASTR_STR,
    KASTR_LIST,
};
enum KASTR_OPT {
    KASTR_POLICY_EXIT = 1, //default
    KASTR_POLICY_CONTINUE = 2,
};
enum KASTR_CONF {
    KASTR_MAX_ARGS = 6,
};


static void kastr_assert_s(int condition, const char *fmt, ...) {
    (void) fmt;
    assert(condition);
}
static void kastr_assert_h(int condition, const char *fmt, ...) {
    (void) fmt;
    assert(condition);
}
static struct kastr_str *kastr_as_str(struct kastr_obj *obj) {
    kastr_assert_h(obj->u.ktype == KASTR_STR, "kastr_as_str(): invalid argument type, expected string");
    return &obj->u.str;
}
static struct kastr_list *kastr_as_list(struct kastr_obj *obj) {
    kastr_assert_h(obj->u.ktype == KASTR_LIST, "kastr_as_list(): invalid argument type, expected list");
    return &obj->u.list;
}

#include "hasht/third_party/strhash/superfasthash.h"

/*hashtable defs*/
    typedef struct kastr_str    vars_hasht_key_type;   //internal notes: there is no indirection, init/deinit must be used
    typedef struct kastr_obj  * vars_hasht_value_type; //                there is indirection,    new/destroy must be used
    int vars_hasht_key_eq_cmp(vars_hasht_key_type *key_1, vars_hasht_key_type *key_2) {
        struct kastr_str *str1 = key_1;
        struct kastr_str *str2 = key_2;
        if (str1->len != str2->len)
            return 1;
        return memcmp(str1->str, str2->str, str1->len); //0 if eq
    }
    size_t vars_hasht_hash(vars_hasht_key_type *key) {
        struct kastr_str *str = key;
        return SuperFastHash(str->str, str->len);
    }

    typedef void * mem_hasht_key_type; 
    typedef unsigned char mem_hasht_value_type; //we don't really need a value, it is a set
    int mem_hasht_key_eq_cmp(mem_hasht_key_type *key_1, mem_hasht_key_type *key_2) {
        //we are comparing two void pointers
        if (*key_1 == *key_2)
            return 0; 
        return 1;
    }
    size_t mem_hasht_hash(mem_hasht_key_type *key) {
        return (uintptr_t) *key; //casting a void ptr to an integer
    }
/*end of hashtable defs*/

#include "vars_hasht.h" //autogenerated and prefixed by vars_
#include "mem_hasht.h"  //autogenerated and prefixed by mem_

struct kastr {
    struct vars_hasht vars_ht;
    struct mem_hasht mem_ht;
    char *err_msg;
    unsigned char is_err_msg_owned;
    int err;
    int err_policy;
};


//fwd
static int kastr_error(struct kastr *kastr, int err_type, const char *fmt, ...);

//TODO: make sure no leaks occur during failures of these functions
//      make sure error reporting works in low memory conditions
static int kastrx_register_new_ptr_(struct kastr *kastr, void *m) {
    unsigned char v = 0;
    int rv = mem_hasht_insert(&kastr->mem_ht, &m, &v);
    if (rv != MEM_HASHT_OK) {
        return kastr_error(kastr, KASTR_RUNTIME_ERR, "kastrx_register_new_ptr_(): mem_hasht_insert() failed");
    }
    return KASTR_OK;
}
static int kastrx_unregister_ptr_(struct kastr *kastr, void *m) {
    unsigned char v = 0;
    int rv = mem_hasht_remove(&kastr->mem_ht, &m);
    if (rv != MEM_HASHT_OK) {
        if (rv == MEM_HASHT_NOT_FOUND) {
            return kastr_error(kastr, KASTR_RUNTIME_ERR, "kastrx_remove_ptr_(): key not found, trying to unregister an unregistered pointer");
        }
        return kastr_error(kastr, KASTR_RUNTIME_ERR, "kastrx_remove_ptr_(): hasht_find() failed");
    }
    return KASTR_OK;
}
static int kastrx_update_ptr_(struct kastr *kastr, void *old_m, void *new_m) {
    if (old_m == new_m)
        return KASTR_OK;
    int rv = KASTR_OK;
    if (old_m != NULL)
        rv = kastrx_unregister_ptr_(kastr, old_m);
    if (rv != KASTR_OK)
        return rv;
    if (new_m == NULL)
        return KASTR_OK;
    return kastrx_register_new_ptr_(kastr, new_m);
}

//untracked allocation
static int kastrx_rfree(struct kastr *kastr, void *p) {
    (void) kastr;
    free(p);
    return KASTR_OK;
}
static int kastrx_rmalloc(struct kastr *kastr, size_t sz, void **m) {
    kastr_assert_h(sz, "kastr_malloc(): 0 size passed");
    void *p = malloc(sz);
    *m = NULL;
    if (!p)
        return kastr_error(kastr, KASTR_NOMEM, "kastrx_malloc(): malloc() returned NULL");
    *m = p;
    return KASTR_OK;
}
static int kastrx_rstrdup(struct kastr *kastr, const char *s, char **out_s) {
    (void) kastr;
    kastr_assert_h(!!s, "passed null string to kastrx_rstrdup()");
    size_t len = strlen(s);
    void *p;
    int rv = kastrx_rmalloc(kastr, len + 1, &p);
    *out_s = p;
    if (rv != KASTR_OK) {
        return rv;
    }
    memcpy(*out_s, s, len);
    (*out_s)[len] = 0;
    return KASTR_OK;
}
static int kastrx_rrealloc(struct kastr *kastr, void *p, size_t sz, void **m) {
    if (!sz) {
        int rv = kastrx_rfree(kastr, p);
        *m = NULL;
        return rv;
    }
    void *np = realloc(p, sz);
    if (!np) {
        return kastr_error(kastr, KASTR_NOMEM, "kastrx_realloc(): realloc() returned NULL");
    }
    *m = np;
    return KASTR_OK;
}

//tracked allocation
static int kastrx_tmalloc(struct kastr *kastr, size_t sz, void **m) {
    int rv = kastrx_rmalloc(kastr, sz, m);
    if (rv != KASTR_OK) {
        return rv;
    }
    rv = kastrx_register_new_ptr_(kastr, *m);
    if (rv != KASTR_OK) {
        kastrx_rfree(kastr, *m);
        return rv;
    }
    return KASTR_OK;
}
static int kastrx_tfree(struct kastr *kastr, void *p) {
    if (!p)
        return KASTR_OK;
    int rv = kastrx_unregister_ptr_(kastr, p);
    kastrx_rfree(kastr, p);
    return rv;
}
static int kastrx_trealloc(struct kastr *kastr, void *p, size_t sz, void **m) {
    int rv = kastrx_rrealloc(kastr, p, sz, m);
    if (rv != KASTR_OK) {
        return rv;
    }
    rv = kastrx_update_ptr_(kastr, p, *m);
    return rv;
}




static int kastrx_str_init(struct kastr *kastr, struct kastr_str *str) {
    (void) kastr;
    str->ktype = KASTR_STR;
    str->str = NULL;
    str->cap = 0;
    str->len = 0;
    return KASTR_OK;
}


static int kastrx_str_init_const_str(struct kastr *kastr, struct kastr_str *str, const char *src0) {
    (void) kastr;
    kastr_assert_h(!!src0, "passed NULL string");
    str->str = (char *) src0;
    str->len = strlen(src0);
    str->cap = -1;
    return KASTR_OK;
}

static int kastrx_str_deinit(struct kastr *kastr, struct kastr_str *str) {
    if (str->cap >= 0) {
        kastrx_tfree(kastr, str->str);
    }
    str->str = NULL;
    str->cap = 0;
    str->len = 0;
    return KASTR_OK;
}

static int kastrx_str_new(struct kastr *kastr, struct kastr_str **strp) {
    void *p = NULL;
    int rv = kastrx_tmalloc(kastr, sizeof(struct kastr_str), &p);
    if (rv != KASTR_OK) {
        *strp = NULL;
        return rv;
    }
    rv = kastrx_str_init(kastr, p);
    *strp = p;
    return rv;
}
static int kastrx_str_destroy(struct kastr *kastr, struct kastr_str *strp) {
    int rv = kastrx_str_deinit(kastr, strp);
    int rv2 = kastrx_tfree(kastr, strp);
    if (rv != KASTR_OK)
        return rv;
    return rv2;
}

static int kastrx_str_clear(struct kastr *kastr, struct kastr_str *str) {
    (void) kastr;
    if (str->cap >= 0) {
        str->str[0] = 0;
        str->len = 0;
    }
    else {
        str->str = "";
        str->len = 0;
        str->cap = -1;
    }
    return KASTR_OK;
}
static int kastrx_str_set_cap(struct kastr *kastr, struct kastr_str *str, int capacity) {
    if (capacity == 0) {
        return kastrx_str_clear(kastr, str);
    }
    if (str->cap < 0) {
        void *p;
        int rv  = kastrx_tmalloc(kastr, capacity, &p);
        if (rv != KASTR_OK) {
            return rv;
        }
        memcpy(p, str->str, str->len);
        str->str = p;
        str->str[str->len] = 0;
    }
    else {
        void *p;
        int rv = kastrx_trealloc(kastr, str->str, capacity, &p);
        if (rv != KASTR_OK) {
            return rv;
        }
        str->str = p;
    }
    str->cap = capacity;
    return KASTR_OK;
}
static int kastrx_str_strlcpy(struct kastr *kastr, struct kastr_str *str, const char *src, int srclen) {
    int rv;
    if (str->cap <= str->len) {
        rv = kastrx_str_set_cap(kastr, str, srclen + 1);
        if (rv != KASTR_OK) {
            return rv;
        }
    }
    memcpy(str->str, src, srclen);
    str->len = srclen;
    str->str[str->len] = 0;
    return KASTR_OK;
}
static int kastrx_str_strlappend(struct kastr *kastr, struct kastr_str *str, const char *src, int srclen) {
    int rv;
    if (str->cap <= (str->len + srclen)) {
        rv = kastrx_str_set_cap(kastr, str, str->len + srclen + 1);
        if (rv != KASTR_OK) {
            return rv;
        }
    }
    memcpy(str->str + str->len, src, srclen);
    str->len += srclen;
    str->str[str->len] = 0;
    return KASTR_OK;
}
static int kastrx_str_strcpy(struct kastr *kastr, struct kastr_str *str, const char *src0) {
    return kastrx_str_strlcpy(kastr, str, src0, strlen(src0));
}
static int kastrx_str_strappend(struct kastr *kastr, struct kastr_str *str, const char *src0) {
    return kastrx_str_strlappend(kastr, str, src0, strlen(src0));
}

static int kastrx_str_init_strcpy(struct kastr *kastr, struct kastr_str *str, const char *src0) {
    int rv = kastrx_str_init(kastr, str);
    if (rv != KASTR_OK)
        return rv;
    rv = kastrx_str_strcpy(kastr, str, src0);
    if (rv != KASTR_OK) {
        kastrx_str_deinit(kastr, str);
        return rv;
    }
    return KASTR_OK;
}

static int kastrx_getvar_(struct kastr *kastr, const char *varname, struct kastr_obj **objp) {

    struct kastr_str key;
    int rv = kastrx_str_init_const_str(kastr, &key, varname);
    if (rv != KASTR_OK) {
        return rv;
    }
    struct vars_hasht_iter iter;
    rv = vars_hasht_find(&kastr->vars_ht, &key, &iter);
    if (rv != VARS_HASHT_OK) {
        if (rv == VARS_HASHT_NOT_FOUND) 
            return kastr_error(kastr, KASTR_NOT_FOUND_ERR, "variable '%s' is undefined", varname);
        else 
            return kastr_error(kastr, KASTR_RUNTIME_ERR, "an error occured while trying to lookup a variable in vars_hasht_find()");
    }
    *objp = iter.pair->value;
    return KASTR_OK;
}
static int kastrx_vardump(struct kastr *kastr, const char *varname) {
    struct kastr_obj *valpo;
    int rv = kastrx_getvar_(kastr, varname, &valpo);
    if (rv == KASTR_OK) {
        if (valpo->u.ktype == KASTR_STR) {
            struct kastr_str *valp = &valpo->u.str;
            printf("'%s'", valp->str);
        }
        else if (valpo->u.ktype == KASTR_LIST) {
            struct kastr_list *valp = &valpo->u.list;
            printf("LIST");
        }
    }
    else {
        printf("NULL");
    }
    printf("\n");
    return rv;
}

static int kastr_vsprintf(struct kastr *kastr, struct kastr_str *str, const char *fmt, va_list ap_in) {
    int fmtlen = strlen(fmt);
    int rv;
    va_list ap;
    if (str->cap < 2) {
        rv = kastrx_str_set_cap(kastr, str, 2);
        if (rv != KASTR_OK) {
            return rv;
        }
    }
    va_copy(ap, ap_in);
    int needed = vsnprintf(str->str, str->cap, fmt, ap);
    va_end(ap);
    if (needed >= str->cap) {
        rv = kastrx_str_set_cap(kastr, str, needed + 1);
        if (rv != KASTR_OK) {
            return rv;
        }
        kastr_assert_s(needed < str->cap, "str grow failed");
        va_copy(ap, ap_in);
        needed = vsnprintf(str->str, str->cap, fmt, ap);
        kastr_assert_s(needed < str->cap, "str grow failed");
        va_end(ap);
    }
    str->len = needed;
    return KASTR_OK;
}
static int kastr_sprintf(struct kastr *kastr, struct kastr_str *str, const char *fmt, ...) {
    va_list ap;
    va_start(ap, fmt);
    int rv = kastr_vsprintf(kastr, str, fmt, ap);
    va_end(ap);
    return rv;
}

static void kastr_clear_error(struct kastr *kastr) {
    kastr->err = 0;
    if (kastr->is_err_msg_owned)
        kastrx_rfree(kastr, kastr->err_msg);
    kastr->err_msg = NULL;
    kastr->is_err_msg_owned = 0;
}
static void kastr_set_error_policy(struct kastr *kastr, int policy) {
    kastr_assert_h(policy == KASTR_POLICY_CONTINUE || policy == KASTR_POLICY_EXIT, "invalid error policy");
    kastr->err_policy = policy;
}
static void kastr_error_act(struct kastr *kastr, int err_type) {
    (void) err_type;
    if (kastr->err_policy == KASTR_POLICY_EXIT) {
        if (kastr->err_msg)
            fprintf(stderr, "%s\n", kastr->err_msg);
        else
            fprintf(stderr, "an unknown error occured (no err msg)\n");
        abort();
        exit(1);
    }
}
static int kastr_error(struct kastr *kastr, int err_type, const char *fmt, ...) {
    kastr_assert_h(err_type, "invalid error code passed (0)");
    if (kastr->err)
        return kastr->err;
    kastr->err = err_type;
    va_list ap;
    struct kastr_str tmp;
    int rv = kastrx_str_init(kastr, &tmp);
    if (rv != KASTR_OK) {
        return rv;
    }
    va_start(ap, fmt);
    rv = kastr_vsprintf(kastr, &tmp, fmt, ap);
    va_end(ap);
    if (rv == KASTR_OK) {
        kastr_assert_h(!!tmp.str, "");
        rv = kastrx_rstrdup(kastr, tmp.str, &kastr->err_msg);
    }
    kastrx_str_deinit(kastr, &tmp);
    kastr_error_act(kastr, err_type);
    return err_type;
}

static int kastrx_init(struct kastr *kastr, int opts) {
    int rv;
    if (opts & KASTR_POLICY_CONTINUE)
        kastr_set_error_policy(kastr, KASTR_POLICY_CONTINUE);
    else 
        kastr_set_error_policy(kastr, KASTR_POLICY_EXIT);

    kastr->err_msg = NULL;
    kastr->err = KASTR_OK;

    rv = mem_hasht_init(&kastr->mem_ht, 256);

    if (rv != MEM_HASHT_OK) {
        rv = kastr_error(kastr, KASTR_RUNTIME_ERR, "couldn't initialize mem hashtable");
        goto end;
    }
    rv = vars_hasht_init(&kastr->vars_ht, 32);
    if (rv != VARS_HASHT_OK) {
        rv = kastr_error(kastr, KASTR_RUNTIME_ERR, "couldn't initialize vars hashtable");
        goto cleanup_mem_ht;
    }

    return KASTR_OK;

cleanup_vars_ht:
    vars_hasht_deinit(&kastr->vars_ht);
cleanup_mem_ht:
    mem_hasht_deinit(&kastr->mem_ht);
end:
    return rv;
}
static int kastrx_deinit(struct kastr *kastr) {
    struct mem_hasht_iter iter;
    int rv = mem_hasht_begin_iterator(&kastr->mem_ht, &iter);
    kastr_assert_h(rv == MEM_HASHT_OK, "kastrx_deinit(): couldnt iterate memory set");
    for (; mem_hasht_iter_check(&iter);  mem_hasht_iter_next(&kastr->mem_ht, &iter)) {
        void *p = iter.pair->key;
        kastrx_rfree(kastr, p);
    }
    mem_hasht_deinit(&kastr->mem_ht);
    vars_hasht_deinit(&kastr->vars_ht);
    return KASTR_OK;
}
static int kastrx_set_str(struct kastr *kastr, const char *key, const char *value) {
    struct kastr_str key_str;
    int rv = kastrx_str_init(kastr, &key_str);
    if (rv != KASTR_OK) {
        return rv;
    }
    rv = kastrx_str_strcpy(kastr, &key_str, key);
    if (rv != KASTR_OK)
        goto cleanup_key;
    struct kastr_str *val_strp;
    rv = kastrx_str_new(kastr, &val_strp);
    if (rv != KASTR_OK) 
        goto cleanup_key;
    rv = kastrx_str_strcpy(kastr, val_strp, value);
    if (rv != KASTR_OK) 
        goto cleanup_val;
    //ownership of key is transferred to the vars hashtable
    struct kastr_obj *objp = (struct kastr_obj *) val_strp; //defined operation?
    rv = vars_hasht_insert(&kastr->vars_ht, &key_str, &objp);
    if (rv != VARS_HASHT_OK) {
        rv = kastr_error(kastr, KASTR_RUNTIME_ERR, "kastrx_set_str(): inserting key into vars hashtable failed");
        goto cleanup_val;
    }
    return KASTR_OK;

cleanup_val:
    kastrx_str_destroy(kastr, val_strp);
cleanup_key:
    kastrx_str_deinit(kastr, &key_str);
    return rv;
}
static int kastrx_get_str(struct kastr *kastr, const char *varname, struct kastr_str **kstrp) {
    struct kastr_obj *objp;
    *kstrp = NULL;
    int rv = kastrx_getvar_(kastr, varname, &objp);
    if (rv != KASTR_OK)
        return rv;
    *kstrp = kastr_as_str(objp);
    return KASTR_OK;
}
struct ka_lexer; //fwd
static int kastrx_lexdump(struct kastr *kastr, struct ka_lexer *lexer) {
    return KASTR_OK;
}
static int kastrx_lexer_init_str(struct kastr *kastr, struct ka_lexer *lex, const char *program) {
    return KASTR_OK;
}
static int kastrx_lexer_deinit(struct kastr *kastr, struct ka_lexer *lex) {
    return KASTR_OK;
}

enum KATOK {
    KAT_STRLITERAL,
    KAT_INTLITERAL,
    KAT_VAR,
    KAT_DOT,
    KAT_EQUALS,
    KAT_OPAREN,
    KAT_CPAREN,
    KAT_OBRACKET,
    KAT_CBRACKET,
    KAT_COMMA,
    KAT_COLON,
    KAT_SEMICOLON,
};
enum KAEXP {
    KAX_CALL,
    KAX_BINARY,
    KAX_UNARY,
    KAX_LITERAL_STR,
    KAX_LITERAL_INT,
    KAX_LITERAL_LIST,
    KAX_LIST_INDEX,
    KAX_LIST_SLICE,
    KAX_VAR_REF,
    KAX_OBJ_DOT,
};
enum KASTMT {
    KAS_CALL,
    KAS_ASSIGN,
    KAS_EMPTY,
};
struct katok {
    int toktype;
    int integer;
    struct kastr_str str;
};
struct kaexpr {
    int exptype;
    union {

        struct kastr_str *str;

        struct kastr_list *list;

        int integer;

        struct { 
            int toktype; //op
            struct kastr_obj *lhs;
            struct kastr_obj *rhs;
        } binary;

        struct { 
            int toktype; //op
            struct kastr_obj *side;
        } unary;

        struct kaexpr *exp;

        struct { 
            struct kaexpr *beg;
            struct kaexpr *end;
        } slice;

        struct kadot { 
            struct kastr_str *str;
            struct kadot *next;
        };
        struct kaprefix { 
            struct kaexpr *start;
            struct kadot *rest;
        } prefix;

        // foo  . bar   .baz    
        //              _kadot_
        //     _kadot__________
        //_prefix______________
        //
        struct kacall *call;

        /*
        KAX_CALL: call
        KAX_BINARY: binary
        KAX_UNARY: unary
        KAX_LITERAL_STR: str
        KAX_LITERAL_INT: integer
        KAX_LITERAL_LIST: list
        KAX_VAR_REF: str
        KAX_LIST_INDEX: exp
        KAX_LIST_SLICE: slice
        KAX_OBJ_DOT: prefix
        */

    } u;
};
struct kafunc_args {
    struct kaexpr args[KASTR_MAX_ARGS];
    int nargs;
};
typedef struct kastr_obj * ( *kafunc_type )(struct kastr *, struct kafunc_args *);
struct kafunc {
    kafunc_type fptr;
};
struct kacall {
    struct kaexpr *called;
    struct kafunc_args args;
};
struct kastrloc {
    struct kastr_str *fname;
    int lineno;
    int colno;
};
struct kastmt {
    int stmttype;
    struct kastrloc loc;
    union {
        struct kacall call;
        struct { 
            struct kaexpr *lvalue;
            struct kaexpr *exp;
        } assign;
    } u;
};
struct kachunk { 
    struct kastmt *stmts;
    int stmt_len;
    int stmt_cap;
};

struct ka_exec_state {
    int ip;
    struct kachunk *chunk;
};

struct ka_lexer {
    struct kastr_str *filename;
    int lineno;
    int colno;
    struct katok cur_token;
    struct katok la_token;
};


/*
    {A} means 0 or more As, and [A] means an optional A.

	program ::= block

	block ::= {stat} [retstat]

	stat ::=  ‘;’ | 
		 varlist ‘=’ explist | 
		 functioncall | 

	funcname ::= Name {‘.’ Name} [‘:’ Name]

	exp ::=  nil | false | true | Numeral | LiteralString | ‘...’ | functiondef | 
		 prefixexp | tableconstructor | exp binop exp | unop exp 

	varlist ::= var {‘,’ var}

	var ::=  Name | prefixexp ‘[’ exp ‘]’ | prefixexp ‘.’ Name 

	namelist ::= Name {‘,’ Name}

	explist ::= exp {‘,’ exp}


	prefixexp ::= var | functioncall | ‘(’ exp ‘)’

	functioncall ::=  prefixexp args | prefixexp ‘:’ Name args 

	args ::=  ‘(’ [explist] ‘)’ | tableconstructor | LiteralString 

	functiondef ::= function funcbody

	funcbody ::= ‘(’ [parlist] ‘)’ block end

	parlist ::= namelist [‘,’ ‘...’] | ‘...’


	fieldlist ::= field {fieldsep field} [fieldsep]

	field ::= ‘[’ exp ‘]’ ‘=’ exp | Name ‘=’ exp | exp

	fieldsep ::= ‘,’ | ‘;’

	binop ::=  ‘+’ | ‘-’ | ‘*’ | ‘/’ | ‘//’ | ‘^’ | ‘%’ | 
		 ‘&’ | ‘~’ | ‘|’ | ‘>>’ | ‘<<’ | ‘..’ | 
		 ‘<’ | ‘<=’ | ‘>’ | ‘>=’ | ‘==’ | ‘~=’ | 
		 and | or

	unop ::= ‘-’ | not | ‘#’ | ‘~’

 * */


static int kastrx_lexer_init_str(struct kastr *kastr, struct ka_lexer *lex, const char *program);
static int kastrx_lexer_deinit(struct kastr *kastr, struct ka_lexer *lex);
static int kastrx_eval(struct kastr *kastr, const char *program) {
    struct ka_lexer lexer;
    kastrx_lexer_init_str(kastr, &lexer, program);
    kastrx_lexdump(kastr, &lexer);
    kastrx_lexer_deinit(kastr, &lexer);
    return KASTR_OK; //dummy
}

/*
//
//program 1
int main(int argc, const char **argv) {
    struct kastr kastr;
}
//with macro sugar
int main(int argc, const char **argv) {
    kastr_start(); //macro, creates a local struct named kastr,
    kastr_set_str("name","john"); //short for kastrx_init(&kastr, ...)
    kastr_eval("result = 'hello {name}!';");
    char *result = kastr_get_str("result");
    kastr_end(); //macro, destroys local struct
}

//program 2
int main(int argc, const char **argv) {
    struct kastr kastr;
    kastrx_init(&kastr);
    const char *input_colors = "black,white,red,green,";
    const char *input_email = "  foo@gmail.com ";

    kastrx_set_str(&kastr, "colors", input_colors); 
    kastrx_set_str(&kastr, "email", input_email); 
    kastrx_eval(&kastr, "clist = colors.split(',');"
                      "email = email.strip();"
                      "email_part = email[0:email.find('@')];");
    char *email_part = kastrx_get_str(&kastr, "email_part");
    struct kastr_list *list = kastrx_get_list(&kastr, "clist");
    for (int i=0; i<list->len; i++) {
        printf("color: %s\n", list->items[i]);
    }
    printf("email first part: %s\n", email_part);
    kastrx_deinit(&kastr); //frees all memory
}
//with macro sugar
int main(int argc, const char **argv) {
    kastr_start(); //macro, creates a local struct named kastr,
    const char *input_colors = "black,white,red,green,";
    const char *input_email = "  foo@gmail.com ";

    kastr_set_str("colors", input_colors); 
    kastr_set_str("email", input_email); 
    kastr_eval("clist = colors.split(',');"
              "email = email.strip();"
              "email_part = email[0:email.find('@')];");
    char *email_part = kastr_get_str("email_part");
    struct kastr_list *list = kastr_get_list("clist");
    for (int i=0; i<list->len; i++) {
        printf("color: %s\n", list->items[i].str);
    }
    printf("email first part: %s\n", email_part);
    kastr_end(); //frees all memory
}
*/
